[jenkins]
jenkins-server ansible_host=JENKINS_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/shopwave.pem

[app_nodes]
node-1 ansible_host=NODE1_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/shopwave.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
